"""empty message

Revision ID: 947e1b97d3fa
Revises: 1b258cc48bc5
Create Date: 2025-03-03 00:07:16.837251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '947e1b97d3fa'
down_revision: Union[str, None] = '1b258cc48bc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(), nullable=True))
    op.drop_column('users', 'number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('number', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
